// Main featured categories - shown prominently in navbar
export const MAIN_CATEGORIES = [
  { id: 'all', name: 'All Papers', shortName: 'all', icon: '📚' },
  { id: 'cs.AI', name: 'Artificial Intelligence', shortName: 'ai', icon: '🤖' },
  { id: 'cs.LG', name: 'Machine Learning', shortName: 'ml', icon: '🧠' },
  { id: 'cs.CL', name: 'Natural Language Processing', shortName: 'nlp', icon: '💬' },
  { id: 'cs.CV', name: 'Computer Vision', shortName: 'vision', icon: '👁️' },
  { id: 'cs.RO', name: 'Robotics', shortName: 'robotics', icon: '🤖' },
  { id: 'stat.ML', name: 'Statistics/ML', shortName: 'stats', icon: '📊' },
  { id: 'math', name: 'Mathematics', shortName: 'math', icon: '📐' },
  { id: 'physics', name: 'Physics', shortName: 'physics', icon: '⚛️' },
  { id: 'quant-ph', name: 'Quantum Physics', shortName: 'quantum', icon: '⚡' },
];

// All categories organized by subject area
export const ALL_CATEGORIES = {
  'Computer Science': [
    { id: 'cs.AI', name: 'Artificial Intelligence' },
    { id: 'cs.AR', name: 'Hardware Architecture' },
    { id: 'cs.CC', name: 'Computational Complexity' },
    { id: 'cs.CE', name: 'Computational Engineering' },
    { id: 'cs.CG', name: 'Computational Geometry' },
    { id: 'cs.CL', name: 'Computation and Language' },
    { id: 'cs.CR', name: 'Cryptography and Security' },
    { id: 'cs.CV', name: 'Computer Vision' },
    { id: 'cs.CY', name: 'Computers and Society' },
    { id: 'cs.DB', name: 'Databases' },
    { id: 'cs.DC', name: 'Distributed Computing' },
    { id: 'cs.DL', name: 'Digital Libraries' },
    { id: 'cs.DM', name: 'Discrete Mathematics' },
    { id: 'cs.DS', name: 'Data Structures and Algorithms' },
    { id: 'cs.ET', name: 'Emerging Technologies' },
    { id: 'cs.FL', name: 'Formal Languages' },
    { id: 'cs.GL', name: 'General Literature' },
    { id: 'cs.GR', name: 'Graphics' },
    { id: 'cs.GT', name: 'Computer Science and Game Theory' },
    { id: 'cs.HC', name: 'Human-Computer Interaction' },
    { id: 'cs.IR', name: 'Information Retrieval' },
    { id: 'cs.IT', name: 'Information Theory' },
    { id: 'cs.LG', name: 'Machine Learning' },
    { id: 'cs.LO', name: 'Logic in Computer Science' },
    { id: 'cs.MA', name: 'Multiagent Systems' },
    { id: 'cs.MM', name: 'Multimedia' },
    { id: 'cs.MS', name: 'Mathematical Software' },
    { id: 'cs.NA', name: 'Numerical Analysis' },
    { id: 'cs.NE', name: 'Neural and Evolutionary Computing' },
    { id: 'cs.NI', name: 'Networking and Internet Architecture' },
    { id: 'cs.OH', name: 'Other Computer Science' },
    { id: 'cs.OS', name: 'Operating Systems' },
    { id: 'cs.PF', name: 'Performance' },
    { id: 'cs.PL', name: 'Programming Languages' },
    { id: 'cs.RO', name: 'Robotics' },
    { id: 'cs.SC', name: 'Symbolic Computation' },
    { id: 'cs.SD', name: 'Sound' },
    { id: 'cs.SE', name: 'Software Engineering' },
    { id: 'cs.SI', name: 'Social and Information Networks' },
    { id: 'cs.SY', name: 'Systems and Control' },
  ],
  'Mathematics': [
    { id: 'math.AG', name: 'Algebraic Geometry' },
    { id: 'math.AT', name: 'Algebraic Topology' },
    { id: 'math.AP', name: 'Analysis of PDEs' },
    { id: 'math.CT', name: 'Category Theory' },
    { id: 'math.CA', name: 'Classical Analysis and ODEs' },
    { id: 'math.CO', name: 'Combinatorics' },
    { id: 'math.AC', name: 'Commutative Algebra' },
    { id: 'math.CV', name: 'Complex Variables' },
    { id: 'math.DG', name: 'Differential Geometry' },
    { id: 'math.DS', name: 'Dynamical Systems' },
    { id: 'math.FA', name: 'Functional Analysis' },
    { id: 'math.GM', name: 'General Mathematics' },
    { id: 'math.GN', name: 'General Topology' },
    { id: 'math.GT', name: 'Geometric Topology' },
    { id: 'math.GR', name: 'Group Theory' },
    { id: 'math.HO', name: 'History and Overview' },
    { id: 'math.IT', name: 'Information Theory' },
    { id: 'math.KT', name: 'K-Theory and Homology' },
    { id: 'math.LO', name: 'Logic' },
    { id: 'math.MP', name: 'Mathematical Physics' },
    { id: 'math.MG', name: 'Metric Geometry' },
    { id: 'math.NT', name: 'Number Theory' },
    { id: 'math.NA', name: 'Numerical Analysis' },
    { id: 'math.OA', name: 'Operator Algebras' },
    { id: 'math.OC', name: 'Optimization and Control' },
    { id: 'math.PR', name: 'Probability' },
    { id: 'math.QA', name: 'Quantum Algebra' },
    { id: 'math.RT', name: 'Representation Theory' },
    { id: 'math.RA', name: 'Rings and Algebras' },
    { id: 'math.SP', name: 'Spectral Theory' },
    { id: 'math.ST', name: 'Statistics Theory' },
    { id: 'math.SG', name: 'Symplectic Geometry' },
  ],
  'Physics': [
    { id: 'astro-ph', name: 'Astrophysics' },
    { id: 'astro-ph.CO', name: 'Cosmology and Nongalactic Astrophysics' },
    { id: 'astro-ph.EP', name: 'Earth and Planetary Astrophysics' },
    { id: 'astro-ph.GA', name: 'Astrophysics of Galaxies' },
    { id: 'astro-ph.HE', name: 'High Energy Astrophysical Phenomena' },
    { id: 'astro-ph.IM', name: 'Instrumentation and Methods for Astrophysics' },
    { id: 'astro-ph.SR', name: 'Solar and Stellar Astrophysics' },
    { id: 'cond-mat.dis-nn', name: 'Disordered Systems and Neural Networks' },
    { id: 'cond-mat.mes-hall', name: 'Mesoscale and Nanoscale Physics' },
    { id: 'cond-mat.mtrl-sci', name: 'Materials Science' },
    { id: 'cond-mat.other', name: 'Other Condensed Matter' },
    { id: 'cond-mat.quant-gas', name: 'Quantum Gases' },
    { id: 'cond-mat.soft', name: 'Soft Condensed Matter' },
    { id: 'cond-mat.stat-mech', name: 'Statistical Mechanics' },
    { id: 'cond-mat.str-el', name: 'Strongly Correlated Electrons' },
    { id: 'cond-mat.supr-con', name: 'Superconductivity' },
    { id: 'gr-qc', name: 'General Relativity and Quantum Cosmology' },
    { id: 'hep-ex', name: 'High Energy Physics - Experiment' },
    { id: 'hep-lat', name: 'High Energy Physics - Lattice' },
    { id: 'hep-ph', name: 'High Energy Physics - Phenomenology' },
    { id: 'hep-th', name: 'High Energy Physics - Theory' },
    { id: 'math-ph', name: 'Mathematical Physics' },
    { id: 'nlin.AO', name: 'Adaptation and Self-Organizing Systems' },
    { id: 'nlin.CD', name: 'Chaotic Dynamics' },
    { id: 'nlin.CG', name: 'Cellular Automata and Lattice Gases' },
    { id: 'nlin.PS', name: 'Pattern Formation and Solitons' },
    { id: 'nlin.SI', name: 'Exactly Solvable and Integrable Systems' },
    { id: 'nucl-ex', name: 'Nuclear Experiment' },
    { id: 'nucl-th', name: 'Nuclear Theory' },
    { id: 'physics.acc-ph', name: 'Accelerator Physics' },
    { id: 'physics.ao-ph', name: 'Atmospheric and Oceanic Physics' },
    { id: 'physics.app-ph', name: 'Applied Physics' },
    { id: 'physics.atm-clus', name: 'Atomic and Molecular Clusters' },
    { id: 'physics.atom-ph', name: 'Atomic Physics' },
    { id: 'physics.bio-ph', name: 'Biological Physics' },
    { id: 'physics.chem-ph', name: 'Chemical Physics' },
    { id: 'physics.class-ph', name: 'Classical Physics' },
    { id: 'physics.comp-ph', name: 'Computational Physics' },
    { id: 'physics.data-an', name: 'Data Analysis' },
    { id: 'physics.flu-dyn', name: 'Fluid Dynamics' },
    { id: 'physics.gen-ph', name: 'General Physics' },
    { id: 'physics.geo-ph', name: 'Geophysics' },
    { id: 'physics.hist-ph', name: 'History and Philosophy of Physics' },
    { id: 'physics.ins-det', name: 'Instrumentation and Detectors' },
    { id: 'physics.med-ph', name: 'Medical Physics' },
    { id: 'physics.optics', name: 'Optics' },
    { id: 'physics.ed-ph', name: 'Physics Education' },
    { id: 'physics.soc-ph', name: 'Physics and Society' },
    { id: 'physics.plasm-ph', name: 'Plasma Physics' },
    { id: 'physics.pop-ph', name: 'Popular Physics' },
    { id: 'physics.space-ph', name: 'Space Physics' },
    { id: 'quant-ph', name: 'Quantum Physics' },
  ],
  'Statistics': [
    { id: 'stat.AP', name: 'Applications' },
    { id: 'stat.CO', name: 'Computation' },
    { id: 'stat.ML', name: 'Machine Learning' },
    { id: 'stat.ME', name: 'Methodology' },
    { id: 'stat.OT', name: 'Other Statistics' },
    { id: 'stat.TH', name: 'Statistics Theory' },
  ],
  'Electrical Engineering': [
    { id: 'eess.AS', name: 'Audio and Speech Processing' },
    { id: 'eess.IV', name: 'Image and Video Processing' },
    { id: 'eess.SP', name: 'Signal Processing' },
    { id: 'eess.SY', name: 'Systems and Control' },
  ],
  'Economics': [
    { id: 'econ.EM', name: 'Econometrics' },
    { id: 'econ.GN', name: 'General Economics' },
    { id: 'econ.TH', name: 'Theoretical Economics' },
  ],
  'Quantitative Biology': [
    { id: 'q-bio.BM', name: 'Biomolecules' },
    { id: 'q-bio.CB', name: 'Cell Behavior' },
    { id: 'q-bio.GN', name: 'Genomics' },
    { id: 'q-bio.MN', name: 'Molecular Networks' },
    { id: 'q-bio.NC', name: 'Neurons and Cognition' },
    { id: 'q-bio.OT', name: 'Other Quantitative Biology' },
    { id: 'q-bio.PE', name: 'Populations and Evolution' },
    { id: 'q-bio.QM', name: 'Quantitative Methods' },
    { id: 'q-bio.SC', name: 'Subcellular Processes' },
    { id: 'q-bio.TO', name: 'Tissues and Organs' },
  ],
  'Quantitative Finance': [
    { id: 'q-fin.CP', name: 'Computational Finance' },
    { id: 'q-fin.EC', name: 'Economics' },
    { id: 'q-fin.GN', name: 'General Finance' },
    { id: 'q-fin.MF', name: 'Mathematical Finance' },
    { id: 'q-fin.PM', name: 'Portfolio Management' },
    { id: 'q-fin.PR', name: 'Pricing of Securities' },
    { id: 'q-fin.RM', name: 'Risk Management' },
    { id: 'q-fin.ST', name: 'Statistical Finance' },
    { id: 'q-fin.TR', name: 'Trading and Market Microstructure' },
  ],
};

// Legacy export for backward compatibility
export const CATEGORIES = MAIN_CATEGORIES;

export const CATEGORY_MAP = {
  // Computer Science
  "cs.AI": "Artificial Intelligence",
  "cs.AR": "Hardware Architecture",
  "cs.CC": "Computational Complexity",
  "cs.CE": "Computational Engineering",
  "cs.CG": "Computational Geometry",
  "cs.CL": "Computation and Language",
  "cs.CR": "Cryptography and Security",
  "cs.CV": "Computer Vision",
  "cs.CY": "Computers and Society",
  "cs.DB": "Databases",
  "cs.DC": "Distributed Computing",
  "cs.DL": "Digital Libraries",
  "cs.DM": "Discrete Mathematics",
  "cs.DS": "Data Structures and Algorithms",
  "cs.ET": "Emerging Technologies",
  "cs.FL": "Formal Languages",
  "cs.GL": "General Literature",
  "cs.GR": "Graphics",
  "cs.GT": "Computer Science and Game Theory",
  "cs.HC": "Human-Computer Interaction",
  "cs.IR": "Information Retrieval",
  "cs.IT": "Information Theory",
  "cs.LG": "Machine Learning",
  "cs.LO": "Logic in Computer Science",
  "cs.MA": "Multiagent Systems",
  "cs.MM": "Multimedia",
  "cs.MS": "Mathematical Software",
  "cs.NA": "Numerical Analysis",
  "cs.NE": "Neural and Evolutionary Computing",
  "cs.NI": "Networking and Internet Architecture",
  "cs.OH": "Other Computer Science",
  "cs.OS": "Operating Systems",
  "cs.PF": "Performance",
  "cs.PL": "Programming Languages",
  "cs.RO": "Robotics",
  "cs.SC": "Symbolic Computation",
  "cs.SD": "Sound",
  "cs.SE": "Software Engineering",
  "cs.SI": "Social and Information Networks",
  "cs.SY": "Systems and Control",
  // Math
  "math.AG": "Algebraic Geometry",
  "math.AT": "Algebraic Topology",
  "math.AP": "Analysis of PDEs",
  "math.CT": "Category Theory",
  "math.CA": "Classical Analysis and ODEs",
  "math.CO": "Combinatorics",
  "math.AC": "Commutative Algebra",
  "math.CV": "Complex Variables",
  "math.DG": "Differential Geometry",
  "math.DS": "Dynamical Systems",
  "math.FA": "Functional Analysis",
  "math.GM": "General Mathematics",
  "math.GN": "General Topology",
  "math.GT": "Geometric Topology",
  "math.GR": "Group Theory",
  "math.HO": "History and Overview",
  "math.IT": "Information Theory",
  "math.KT": "K-Theory and Homology",
  "math.LO": "Logic",
  "math.MP": "Mathematical Physics",
  "math.MG": "Metric Geometry",
  "math.NT": "Number Theory",
  "math.NA": "Numerical Analysis",
  "math.OA": "Operator Algebras",
  "math.OC": "Optimization and Control",
  "math.PR": "Probability",
  "math.QA": "Quantum Algebra",
  "math.RT": "Representation Theory",
  "math.RA": "Rings and Algebras",
  "math.SP": "Spectral Theory",
  "math.ST": "Statistics Theory",
  "math.SG": "Symplectic Geometry",
  // Physics
  "physics.acc-ph": "Accelerator Physics",
  "physics.ao-ph": "Atmospheric and Oceanic Physics",
  "physics.app-ph": "Applied Physics",
  "physics.atm-clus": "Atomic and Molecular Clusters",
  "physics.atom-ph": "Atomic Physics",
  "physics.bio-ph": "Biological Physics",
  "physics.chem-ph": "Chemical Physics",
  "physics.class-ph": "Classical Physics",
  "physics.comp-ph": "Computational Physics",
  "physics.data-an": "Data Analysis",
  "physics.flu-dyn": "Fluid Dynamics",
  "physics.gen-ph": "General Physics",
  "physics.geo-ph": "Geophysics",
  "physics.hist-ph": "History and Philosophy of Physics",
  "physics.ins-det": "Instrumentation and Detectors",
  "physics.med-ph": "Medical Physics",
  "physics.optics": "Optics",
  "physics.ed-ph": "Physics Education",
  "physics.soc-ph": "Physics and Society",
  "physics.plasm-ph": "Plasma Physics",
  "physics.pop-ph": "Popular Physics",
  "physics.space-ph": "Space Physics",
  // Quantum Physics
  "quant-ph": "Quantum Physics",
  // Statistics
  "stat.AP": "Applications",
  "stat.CO": "Computation",
  "stat.ML": "Machine Learning",
  "stat.ME": "Methodology",
  "stat.OT": "Other Statistics",
  "stat.TH": "Statistics Theory",
  // Electrical Engineering
  "eess.AS": "Audio and Speech Processing",
  "eess.IV": "Image and Video Processing",
  "eess.SP": "Signal Processing",
  "eess.SY": "Systems and Control",
  // Economics
  "econ.EM": "Econometrics",
  "econ.GN": "General Economics",
  "econ.TH": "Theoretical Economics",
};

export function getCategoryName(categoryCode) {
  return CATEGORY_MAP[categoryCode] || categoryCode;
}

export function getCategoryInfo(categoryId) {
  return CATEGORIES.find(cat => categoryId.startsWith(cat.id)) || CATEGORIES[0];
}
