export const CATEGORIES = [
  { id: 'all', name: 'All Papers', icon: '📚' },
  // Computer Science
  { id: 'cs.AI', name: 'Artificial Intelligence', icon: '🤖' },
  { id: 'cs.CL', name: 'Natural Language Processing', icon: '💬' },
  { id: 'cs.CV', name: 'Computer Vision', icon: '👁️' },
  { id: 'cs.LG', name: 'Machine Learning', icon: '🧠' },
  { id: 'cs.RO', name: 'Robotics', icon: '🤖' },
  { id: 'cs.CR', name: 'Security', icon: '🔒' },
  { id: 'cs.SE', name: 'Software Engineering', icon: '💻' },
  // Math/Stats
  { id: 'math.OC', name: 'Optimization', icon: '📈' },
  { id: 'stat.ML', name: 'Statistics/ML', icon: '📊' },
  // Physics
  { id: 'quant-ph', name: 'Quantum Physics', icon: '⚡' },
];

export const CATEGORY_MAP = {
  // Computer Science
  "cs.AI": "Artificial Intelligence",
  "cs.AR": "Hardware Architecture",
  "cs.CC": "Computational Complexity",
  "cs.CE": "Computational Engineering",
  "cs.CG": "Computational Geometry",
  "cs.CL": "Computation and Language",
  "cs.CR": "Cryptography and Security",
  "cs.CV": "Computer Vision",
  "cs.CY": "Computers and Society",
  "cs.DB": "Databases",
  "cs.DC": "Distributed Computing",
  "cs.DL": "Digital Libraries",
  "cs.DM": "Discrete Mathematics",
  "cs.DS": "Data Structures and Algorithms",
  "cs.ET": "Emerging Technologies",
  "cs.FL": "Formal Languages",
  "cs.GL": "General Literature",
  "cs.GR": "Graphics",
  "cs.GT": "Computer Science and Game Theory",
  "cs.HC": "Human-Computer Interaction",
  "cs.IR": "Information Retrieval",
  "cs.IT": "Information Theory",
  "cs.LG": "Machine Learning",
  "cs.LO": "Logic in Computer Science",
  "cs.MA": "Multiagent Systems",
  "cs.MM": "Multimedia",
  "cs.MS": "Mathematical Software",
  "cs.NA": "Numerical Analysis",
  "cs.NE": "Neural and Evolutionary Computing",
  "cs.NI": "Networking and Internet Architecture",
  "cs.OH": "Other Computer Science",
  "cs.OS": "Operating Systems",
  "cs.PF": "Performance",
  "cs.PL": "Programming Languages",
  "cs.RO": "Robotics",
  "cs.SC": "Symbolic Computation",
  "cs.SD": "Sound",
  "cs.SE": "Software Engineering",
  "cs.SI": "Social and Information Networks",
  "cs.SY": "Systems and Control",
  // Math
  "math.AG": "Algebraic Geometry",
  "math.AT": "Algebraic Topology",
  "math.AP": "Analysis of PDEs",
  "math.CT": "Category Theory",
  "math.CA": "Classical Analysis and ODEs",
  "math.CO": "Combinatorics",
  "math.AC": "Commutative Algebra",
  "math.CV": "Complex Variables",
  "math.DG": "Differential Geometry",
  "math.DS": "Dynamical Systems",
  "math.FA": "Functional Analysis",
  "math.GM": "General Mathematics",
  "math.GN": "General Topology",
  "math.GT": "Geometric Topology",
  "math.GR": "Group Theory",
  "math.HO": "History and Overview",
  "math.IT": "Information Theory",
  "math.KT": "K-Theory and Homology",
  "math.LO": "Logic",
  "math.MP": "Mathematical Physics",
  "math.MG": "Metric Geometry",
  "math.NT": "Number Theory",
  "math.NA": "Numerical Analysis",
  "math.OA": "Operator Algebras",
  "math.OC": "Optimization and Control",
  "math.PR": "Probability",
  "math.QA": "Quantum Algebra",
  "math.RT": "Representation Theory",
  "math.RA": "Rings and Algebras",
  "math.SP": "Spectral Theory",
  "math.ST": "Statistics Theory",
  "math.SG": "Symplectic Geometry",
  // Physics
  "physics.acc-ph": "Accelerator Physics",
  "physics.ao-ph": "Atmospheric and Oceanic Physics",
  "physics.app-ph": "Applied Physics",
  "physics.atm-clus": "Atomic and Molecular Clusters",
  "physics.atom-ph": "Atomic Physics",
  "physics.bio-ph": "Biological Physics",
  "physics.chem-ph": "Chemical Physics",
  "physics.class-ph": "Classical Physics",
  "physics.comp-ph": "Computational Physics",
  "physics.data-an": "Data Analysis",
  "physics.flu-dyn": "Fluid Dynamics",
  "physics.gen-ph": "General Physics",
  "physics.geo-ph": "Geophysics",
  "physics.hist-ph": "History and Philosophy of Physics",
  "physics.ins-det": "Instrumentation and Detectors",
  "physics.med-ph": "Medical Physics",
  "physics.optics": "Optics",
  "physics.ed-ph": "Physics Education",
  "physics.soc-ph": "Physics and Society",
  "physics.plasm-ph": "Plasma Physics",
  "physics.pop-ph": "Popular Physics",
  "physics.space-ph": "Space Physics",
  // Quantum Physics
  "quant-ph": "Quantum Physics",
  // Statistics
  "stat.AP": "Applications",
  "stat.CO": "Computation",
  "stat.ML": "Machine Learning",
  "stat.ME": "Methodology",
  "stat.OT": "Other Statistics",
  "stat.TH": "Statistics Theory",
  // Electrical Engineering
  "eess.AS": "Audio and Speech Processing",
  "eess.IV": "Image and Video Processing",
  "eess.SP": "Signal Processing",
  "eess.SY": "Systems and Control",
  // Economics
  "econ.EM": "Econometrics",
  "econ.GN": "General Economics",
  "econ.TH": "Theoretical Economics",
};

export function getCategoryName(categoryCode) {
  return CATEGORY_MAP[categoryCode] || categoryCode;
}

export function getCategoryInfo(categoryId) {
  return CATEGORIES.find(cat => categoryId.startsWith(cat.id)) || CATEGORIES[0];
}
